spring:
    datasource:
        url: jdbc:mysql://localhost:3306/myfinan?useTimezone=true&serverTimezone=America/Sao_Paulo
        username: root
        password: 
        driverClassName: com.mysql.cj.jdbc.Driver
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update